# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

# Build across multiple platforms
#strategy:
#  matrix:
#    linux:
#      imageName: "ubuntu-latest"
#    mac:
#      imageName: "macOS-latest"
#    windows:
#      imageName: "windows-latest"
#  maxParallel: 3
#pool:
#  vmImage: $(imageName)

# Build using different versions on single platform
#pool:
#  vmImage: ubuntu-latest
#strategy:
#  matrix:
#    jdk10:
#      jdkVersion: "1.10"
#    jdk11:
#      jdkVersion: "1.11"
#  maxParallel: 2

# Build on multiple platforms and versions
strategy:
  matrix:
    jdk10_linux:
      imageName: "ubuntu-latest"
      jdkVersion: "1.10"
    jdk11_windows:
      imageName: "windows-latest"
      jdkVersion: "1.11"
  maxParallel: 2

pool:
  vmImage: $(imageName)
  
steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
  
- task: Maven@4
  inputs:
    mavenPomFile: "pom.xml"
    mavenOptions: "-Xmx3072m"
    javaHomeOption: "JDKVersion"
    jdkVersionOption: $(jdkVersion)
    jdkArchitectureOption: "x64"
    publishJUnitResults: true
    testResultsFiles: "**/TEST-*.xml"
    goals: "package"  
